//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.IO;
using NUnit.Framework;
using Cyotek.Data.Nbt.Serialization;

namespace Cyotek.Data.Nbt.Tests.Serialization
{
  partial class BinaryTagReaderTests
  {
    [Test]
    [ExpectedException(typeof(InvalidDataException))]
    public void ReadByte_throws_exception_if_data_invalid()
    {
      using (MemoryStream stream = new MemoryStream())
      {
        // arrange
        TagReader reader;

        reader = this.CreateReader(stream);

        // act
        reader.ReadByte();
      }
    }

    [Test]
    [ExpectedException(typeof(InvalidDataException))]
    public void ReadShort_throws_exception_if_data_invalid()
    {
      using (MemoryStream stream = new MemoryStream())
      {
        // arrange
        TagReader reader;

        reader = this.CreateReader(stream);

        // act
        reader.ReadShort();
      }
    }

    [Test]
    [ExpectedException(typeof(InvalidDataException))]
    public void ReadInt_throws_exception_if_data_invalid()
    {
      using (MemoryStream stream = new MemoryStream())
      {
        // arrange
        TagReader reader;

        reader = this.CreateReader(stream);

        // act
        reader.ReadInt();
      }
    }

    [Test]
    [ExpectedException(typeof(InvalidDataException))]
    public void ReadLong_throws_exception_if_data_invalid()
    {
      using (MemoryStream stream = new MemoryStream())
      {
        // arrange
        TagReader reader;

        reader = this.CreateReader(stream);

        // act
        reader.ReadLong();
      }
    }

    [Test]
    [ExpectedException(typeof(InvalidDataException))]
    public void ReadFloat_throws_exception_if_data_invalid()
    {
      using (MemoryStream stream = new MemoryStream())
      {
        // arrange
        TagReader reader;

        reader = this.CreateReader(stream);

        // act
        reader.ReadFloat();
      }
    }

    [Test]
    [ExpectedException(typeof(InvalidDataException))]
    public void ReadDouble_throws_exception_if_data_invalid()
    {
      using (MemoryStream stream = new MemoryStream())
      {
        // arrange
        TagReader reader;

        reader = this.CreateReader(stream);

        // act
        reader.ReadDouble();
      }
    }

    [Test]
    [ExpectedException(typeof(InvalidDataException))]
    public void ReadByteArray_throws_exception_if_data_invalid()
    {
      using (MemoryStream stream = new MemoryStream())
      {
        // arrange
        TagReader reader;
        TagWriter writer;

        reader = this.CreateReader(stream);
        writer = new BinaryTagWriter(stream);

        // TODO: WriteValue is currently protected
        //writer.WriteValue(100);
        this.WriteValue(stream, 100);

        stream.Position = 0;

        // act
        reader.ReadByteArray();
      }
    }

        [Test]
    [ExpectedException(typeof(InvalidDataException))]
    public void ReadString_throws_exception_if_data_invalid()
    {
      using (MemoryStream stream = new MemoryStream())
      {
        // arrange
        TagReader reader;
        TagWriter writer;

        reader = this.CreateReader(stream);
        writer = new BinaryTagWriter(stream);

        // TODO: WriteValue is currently protected
        //writer.WriteValue((short)100);
        this.WriteValue(stream, (short)100);

        stream.Position = 0;

        // act
        reader.ReadString();
      }
    }

        [Test]
    [ExpectedException(typeof(InvalidDataException))]
    public void ReadList_throws_exception_if_data_invalid()
    {
      using (MemoryStream stream = new MemoryStream())
      {
        // arrange
        TagReader reader;

        reader = this.CreateReader(stream);

        // act
        reader.ReadList();
      }
    }

    [Test]
    [ExpectedException(typeof(InvalidDataException))]
    public void ReadCompound_throws_exception_if_data_invalid()
    {
      using (MemoryStream stream = new MemoryStream())
      {
        // arrange
        TagReader reader;

        reader = this.CreateReader(stream);

        // act
        reader.ReadCompound();
      }
    }

    [Test]
    [ExpectedException(typeof(InvalidDataException))]
    public void ReadIntArray_throws_exception_if_data_invalid()
    {
      using (MemoryStream stream = new MemoryStream())
      {
        // arrange
        TagReader reader;
        TagWriter writer;

        reader = this.CreateReader(stream);
        writer = new BinaryTagWriter(stream);

        // TODO: WriteValue is currently protected
        //writer.WriteValue(100);
        this.WriteValue(stream, 100);

        stream.Position = 0;

        // act
        reader.ReadIntArray();
      }
    }

      }
}
