//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


using NUnit.Framework;

namespace Cyotek.Data.Nbt.Tests
{
  partial class TagLongArrayTests
  {
    [Test]
    public void Constructor_sets_name()
    {
      // arrange
      TagLongArray target;
      string expected;
      string actual;

      expected = "Alphatag";

      // act
      target = new TagLongArray(expected);

      // assert
      actual = target.Name;
      Assert.AreEqual(expected, actual);
    }

    [Test]
    public void Constructor_sets_default_name()
    {
      // arrange
      TagLongArray target;
      string expected;
      string actual;

      expected = string.Empty;

      // act
      target = new TagLongArray();

      // assert
      actual = target.Name;
      Assert.AreEqual(expected, actual);
    }

    [Test]
    public void Constructor_sets_default_value()
    {
      // arrange
      TagLongArray target;
      long[] expected;
      long[] actual;

      expected = new long[0];

      // act
      target = new TagLongArray();

      // assert
      actual = target.Value;
      Assert.AreEqual(expected, actual);
    }

    [Test]
    public void Constructor_sets_value()
    {
      // arrange
      TagLongArray target;
      long[] expected;
      long[] actual;

      expected = new[] { long.MinValue / 2, 2994, long.MaxValue / 2, 4294394 };

      // act
      target = new TagLongArray(string.Empty, expected);

      // assert
      actual = target.Value;
      Assert.AreEqual(expected, actual);
    }

    [Test]
    public void Constructor_sets_value_without_name()
    {
      // arrange
      TagLongArray target;
      long[] expected;
      long[] actual;

      expected = new[] { long.MinValue / 2, 2994, long.MaxValue / 2, 4294394 };

      // act
      target = new TagLongArray(expected);

      // assert
      actual = target.Value;
      Assert.AreEqual(expected, actual);
    }

    [Test]
    public void SetValue_updates_value()
    {
      // arrange
      Tag target;
      long[] expected;
      long[] actual;

      target = new TagLongArray();

      expected = new[] { long.MinValue / 2, 2994, long.MaxValue / 2, 4294394 };

      // act
      target.SetValue(expected);

      // assert
      actual = ((TagLongArray)target).Value;
      Assert.AreEqual(expected, actual);
    }

    [Test]
    public void GetValue_retrieves_value()
    {
      // arrange
      Tag target;
      long[] expected;
      object actual;

      expected = new[] { long.MinValue / 2, 2994, long.MaxValue / 2, 4294394 };

      target = TagFactory.CreateTag(expected);

      // act
      actual = target.GetValue();

      // assert
      Assert.AreEqual(expected, actual);
    }

    [Test]
    public void Equals_returns_true_for_matching_tag()
    {
      // arrange
      TagLongArray target;
      TagLongArray other;
      bool actual;

      target = new TagLongArray("alpha", new[] { long.MinValue / 2, 2994, long.MaxValue / 2, 4294394 });
      other = new TagLongArray("alpha", new[] { long.MinValue / 2, 2994, long.MaxValue / 2, 4294394 });

      // act
      actual = target.Equals(other);

      // assert
      Assert.IsTrue(actual);
    }

    [Test]
    public void Equals_returns_false_with_different_name()
    {
      // arrange
      TagLongArray target;
      TagLongArray other;
      bool actual;

      target = new TagLongArray("Alpha", new[] { long.MinValue / 2, 2994, long.MaxValue / 2, 4294394 });
      other = new TagLongArray("Beta", new[] { long.MinValue / 2, 2994, long.MaxValue / 2, 4294394 });

      // act
      actual = target.Equals(other);

      // assert
      Assert.IsFalse(actual);
    }

    [Test]
    public void Equals_returns_false_with_different_value()
    {
      // arrange
      TagLongArray target;
      TagLongArray other;
      bool actual;

      target = new TagLongArray(string.Empty, new[] { long.MinValue / 2, 2994, long.MaxValue / 2, 4294394 });
      other = new TagLongArray(string.Empty, new[] { long.MinValue / 3, 2994, long.MaxValue / 3, 4294394 });

      // act
      actual = target.Equals(other);

      // assert
      Assert.IsFalse(actual);
    }

    [Test]
    public void Type_returns_correct_value()
    {
      // arrange
      TagLongArray target;
      TagType expected;
      TagType actual;

      target = new TagLongArray();

      expected = TagType.LongArray;

      // act
      actual = target.Type;

      // assert
      Assert.AreEqual(expected, actual);
    }

    [Test]
    public void GetHashCode_returns_same_value_for_matching_tags()
    {
      // arrange
      TagLongArray target;
      int actual;
      int expected;

      target = new TagLongArray("beta", new[] { long.MinValue / 2, 2994, long.MaxValue / 2, 4294394 });

      expected = new TagLongArray("beta", new[] { long.MinValue / 2, 2994, long.MaxValue / 2, 4294394 }).GetHashCode();

      // act
      actual = target.GetHashCode();

      // assert
      Assert.AreEqual(expected, actual);
    }

    [Test]
    public void GetHashCode_returns_different_values_with_different_name()
    {
      // arrange
      TagLongArray target;
      int actual;
      int notExpected;

      target = new TagLongArray("Alpha", new[] { long.MinValue / 2, 2994, long.MaxValue / 2, 4294394 });

      notExpected = new TagLongArray("Beta", new[] { long.MinValue / 2, 2994, long.MaxValue / 2, 4294394 }).GetHashCode();

      // act
      actual = target.GetHashCode();

      // assert
      Assert.AreNotEqual(notExpected, actual);
    }

    [Test]
    public void GetHashCode_returns_different_values_with_different_value()
    {
      // arrange
      TagLongArray target;
      int actual;
      int notExpected;

      target = new TagLongArray(string.Empty, new[] { long.MinValue / 2, 2994, long.MaxValue / 2, 4294394 });

      notExpected = new TagLongArray(string.Empty, new[] { long.MinValue / 3, 2994, long.MaxValue / 3, 4294394 }).GetHashCode();

      // act
      actual = target.GetHashCode();

      // assert
      Assert.AreNotEqual(notExpected, actual);
    }

    [Test]
    public void Value_can_be_set()
    {
      // arrange
      TagLongArray target;
      long[] expected;
      long[] actual;

      expected = new[] { long.MinValue / 2, 2994, long.MaxValue / 2, 4294394 };

      target = new TagLongArray();

      // act
      target.Value = expected;

      // assert
      actual = target.Value;
      Assert.AreEqual(expected, actual);
    }

    [Test]
    public void ToValueString_returns_string_version_of_value()
    {
      // arrange
      TagLongArray target;
      string expected;
      string actual;

      expected = "-4611686018427387904, 2994, 4611686018427387903, 4294394";

      target = new TagLongArray(string.Empty, new[] { long.MinValue / 2, 2994, long.MaxValue / 2, 4294394 });

      // act
      actual = target.ToValueString();

      // assert
      Assert.AreEqual(expected, actual);
    }

    [Test]
    public void ToString_returns_string_version_of_tag()
    {
      // arrange
      TagLongArray target;
      string expected;
      string actual;

      expected = "[LongArray: gamma] (4 items)";

      target = new TagLongArray("gamma", new[] { long.MinValue / 2, 2994, long.MaxValue / 2, 4294394 });

      // act
      actual = target.ToString();

      // assert
      Assert.AreEqual(expected, actual);
    }
  }
}

