//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


using System;

namespace Cyotek.Data.Nbt.Serialization
{
  partial class TagWriter
  {
    /// <summary>
    /// Writes a <see cref="byte" /> value.
    /// </summary>
    /// <param name="value">The <see cref="byte" /> value to write.</param>
    public abstract void WriteValue(byte value);

    /// <summary>
    /// Writes a tag entry for a <see cref="byte" /> value with the specified name.
    /// </summary>
    /// <param name="name">The name of the tag entry to write.</param>
    /// <param name="value">The <see cref="byte" /> value to write.</param>
    public void WriteTag(string name, byte value)
    {
      this.WriteStartTag(TagType.Byte, name);
      this.WriteValue(value);
      this.WriteEndTag();
    }

    /// <summary>
    /// Writes an unnamed tag entry for a <see cref="byte" /> value.
    /// </summary>
    /// <param name="value">The <see cref="byte" /> value to write.</param>
    public void WriteTag(byte value)
    {
      this.WriteStartTag(TagType.Byte, string.Empty, WriteTagOptions.IgnoreName);
      this.WriteValue(value);
      this.WriteEndTag();
    }

    /// <summary>
    /// Writes a <see cref="short" /> value.
    /// </summary>
    /// <param name="value">The <see cref="short" /> value to write.</param>
    public abstract void WriteValue(short value);

    /// <summary>
    /// Writes a tag entry for a <see cref="short" /> value with the specified name.
    /// </summary>
    /// <param name="name">The name of the tag entry to write.</param>
    /// <param name="value">The <see cref="short" /> value to write.</param>
    public void WriteTag(string name, short value)
    {
      this.WriteStartTag(TagType.Short, name);
      this.WriteValue(value);
      this.WriteEndTag();
    }

    /// <summary>
    /// Writes an unnamed tag entry for a <see cref="short" /> value.
    /// </summary>
    /// <param name="value">The <see cref="short" /> value to write.</param>
    public void WriteTag(short value)
    {
      this.WriteStartTag(TagType.Short, string.Empty, WriteTagOptions.IgnoreName);
      this.WriteValue(value);
      this.WriteEndTag();
    }

    /// <summary>
    /// Writes a <see cref="int" /> value.
    /// </summary>
    /// <param name="value">The <see cref="int" /> value to write.</param>
    public abstract void WriteValue(int value);

    /// <summary>
    /// Writes a tag entry for a <see cref="int" /> value with the specified name.
    /// </summary>
    /// <param name="name">The name of the tag entry to write.</param>
    /// <param name="value">The <see cref="int" /> value to write.</param>
    public void WriteTag(string name, int value)
    {
      this.WriteStartTag(TagType.Int, name);
      this.WriteValue(value);
      this.WriteEndTag();
    }

    /// <summary>
    /// Writes an unnamed tag entry for a <see cref="int" /> value.
    /// </summary>
    /// <param name="value">The <see cref="int" /> value to write.</param>
    public void WriteTag(int value)
    {
      this.WriteStartTag(TagType.Int, string.Empty, WriteTagOptions.IgnoreName);
      this.WriteValue(value);
      this.WriteEndTag();
    }

    /// <summary>
    /// Writes a <see cref="long" /> value.
    /// </summary>
    /// <param name="value">The <see cref="long" /> value to write.</param>
    public abstract void WriteValue(long value);

    /// <summary>
    /// Writes a tag entry for a <see cref="long" /> value with the specified name.
    /// </summary>
    /// <param name="name">The name of the tag entry to write.</param>
    /// <param name="value">The <see cref="long" /> value to write.</param>
    public void WriteTag(string name, long value)
    {
      this.WriteStartTag(TagType.Long, name);
      this.WriteValue(value);
      this.WriteEndTag();
    }

    /// <summary>
    /// Writes an unnamed tag entry for a <see cref="long" /> value.
    /// </summary>
    /// <param name="value">The <see cref="long" /> value to write.</param>
    public void WriteTag(long value)
    {
      this.WriteStartTag(TagType.Long, string.Empty, WriteTagOptions.IgnoreName);
      this.WriteValue(value);
      this.WriteEndTag();
    }

    /// <summary>
    /// Writes a <see cref="float" /> value.
    /// </summary>
    /// <param name="value">The <see cref="float" /> value to write.</param>
    public abstract void WriteValue(float value);

    /// <summary>
    /// Writes a tag entry for a <see cref="float" /> value with the specified name.
    /// </summary>
    /// <param name="name">The name of the tag entry to write.</param>
    /// <param name="value">The <see cref="float" /> value to write.</param>
    public void WriteTag(string name, float value)
    {
      this.WriteStartTag(TagType.Float, name);
      this.WriteValue(value);
      this.WriteEndTag();
    }

    /// <summary>
    /// Writes an unnamed tag entry for a <see cref="float" /> value.
    /// </summary>
    /// <param name="value">The <see cref="float" /> value to write.</param>
    public void WriteTag(float value)
    {
      this.WriteStartTag(TagType.Float, string.Empty, WriteTagOptions.IgnoreName);
      this.WriteValue(value);
      this.WriteEndTag();
    }

    /// <summary>
    /// Writes a <see cref="double" /> value.
    /// </summary>
    /// <param name="value">The <see cref="double" /> value to write.</param>
    public abstract void WriteValue(double value);

    /// <summary>
    /// Writes a tag entry for a <see cref="double" /> value with the specified name.
    /// </summary>
    /// <param name="name">The name of the tag entry to write.</param>
    /// <param name="value">The <see cref="double" /> value to write.</param>
    public void WriteTag(string name, double value)
    {
      this.WriteStartTag(TagType.Double, name);
      this.WriteValue(value);
      this.WriteEndTag();
    }

    /// <summary>
    /// Writes an unnamed tag entry for a <see cref="double" /> value.
    /// </summary>
    /// <param name="value">The <see cref="double" /> value to write.</param>
    public void WriteTag(double value)
    {
      this.WriteStartTag(TagType.Double, string.Empty, WriteTagOptions.IgnoreName);
      this.WriteValue(value);
      this.WriteEndTag();
    }

    /// <summary>
    /// Writes a <see cref="byte[]" /> value.
    /// </summary>
    /// <param name="value">The <see cref="byte[]" /> value to write.</param>
    public abstract void WriteValue(byte[] value);

    /// <summary>
    /// Writes a tag entry for a <see cref="byte[]" /> value with the specified name.
    /// </summary>
    /// <param name="name">The name of the tag entry to write.</param>
    /// <param name="value">The <see cref="byte[]" /> value to write.</param>
    public void WriteTag(string name, byte[] value)
    {
      this.WriteStartTag(TagType.ByteArray, name);
      this.WriteValue(value);
      this.WriteEndTag();
    }

    /// <summary>
    /// Writes an unnamed tag entry for a <see cref="byte[]" /> value.
    /// </summary>
    /// <param name="value">The <see cref="byte[]" /> value to write.</param>
    public void WriteTag(byte[] value)
    {
      this.WriteStartTag(TagType.ByteArray, string.Empty, WriteTagOptions.IgnoreName);
      this.WriteValue(value);
      this.WriteEndTag();
    }

    /// <summary>
    /// Writes a <see cref="string" /> value.
    /// </summary>
    /// <param name="value">The <see cref="string" /> value to write.</param>
    public abstract void WriteValue(string value);

    /// <summary>
    /// Writes a tag entry for a <see cref="string" /> value with the specified name.
    /// </summary>
    /// <param name="name">The name of the tag entry to write.</param>
    /// <param name="value">The <see cref="string" /> value to write.</param>
    public void WriteTag(string name, string value)
    {
      this.WriteStartTag(TagType.String, name);
      this.WriteValue(value);
      this.WriteEndTag();
    }

    /// <summary>
    /// Writes an unnamed tag entry for a <see cref="string" /> value.
    /// </summary>
    /// <param name="value">The <see cref="string" /> value to write.</param>
    public void WriteTag(string value)
    {
      this.WriteStartTag(TagType.String, string.Empty, WriteTagOptions.IgnoreName);
      this.WriteValue(value);
      this.WriteEndTag();
    }

    /// <summary>
    /// Writes a <see cref="TagCollection" /> value.
    /// </summary>
    /// <param name="value">The <see cref="TagCollection" /> value to write.</param>
    public abstract void WriteValue(TagCollection value);

    /// <summary>
    /// Writes a tag entry for a <see cref="TagCollection" /> value with the specified name.
    /// </summary>
    /// <param name="name">The name of the tag entry to write.</param>
    /// <param name="value">The <see cref="TagCollection" /> value to write.</param>
    public void WriteTag(string name, TagCollection value)
    {
      this.WriteStartTag(TagType.List, name);
      this.WriteValue(value);
      this.WriteEndTag();
    }

    /// <summary>
    /// Writes an unnamed tag entry for a <see cref="TagCollection" /> value.
    /// </summary>
    /// <param name="value">The <see cref="TagCollection" /> value to write.</param>
    public void WriteTag(TagCollection value)
    {
      this.WriteStartTag(TagType.List, string.Empty, WriteTagOptions.IgnoreName);
      this.WriteValue(value);
      this.WriteEndTag();
    }

    /// <summary>
    /// Writes a <see cref="TagDictionary" /> value.
    /// </summary>
    /// <param name="value">The <see cref="TagDictionary" /> value to write.</param>
    public abstract void WriteValue(TagDictionary value);

    /// <summary>
    /// Writes a tag entry for a <see cref="TagDictionary" /> value with the specified name.
    /// </summary>
    /// <param name="name">The name of the tag entry to write.</param>
    /// <param name="value">The <see cref="TagDictionary" /> value to write.</param>
    public void WriteTag(string name, TagDictionary value)
    {
      this.WriteStartTag(TagType.Compound, name);
      this.WriteValue(value);
      this.WriteEndTag();
    }

    /// <summary>
    /// Writes an unnamed tag entry for a <see cref="TagDictionary" /> value.
    /// </summary>
    /// <param name="value">The <see cref="TagDictionary" /> value to write.</param>
    public void WriteTag(TagDictionary value)
    {
      this.WriteStartTag(TagType.Compound, string.Empty, WriteTagOptions.IgnoreName);
      this.WriteValue(value);
      this.WriteEndTag();
    }

    /// <summary>
    /// Writes a <see cref="int[]" /> value.
    /// </summary>
    /// <param name="value">The <see cref="int[]" /> value to write.</param>
    public abstract void WriteValue(int[] value);

    /// <summary>
    /// Writes a tag entry for a <see cref="int[]" /> value with the specified name.
    /// </summary>
    /// <param name="name">The name of the tag entry to write.</param>
    /// <param name="value">The <see cref="int[]" /> value to write.</param>
    public void WriteTag(string name, int[] value)
    {
      this.WriteStartTag(TagType.IntArray, name);
      this.WriteValue(value);
      this.WriteEndTag();
    }

    /// <summary>
    /// Writes an unnamed tag entry for a <see cref="int[]" /> value.
    /// </summary>
    /// <param name="value">The <see cref="int[]" /> value to write.</param>
    public void WriteTag(int[] value)
    {
      this.WriteStartTag(TagType.IntArray, string.Empty, WriteTagOptions.IgnoreName);
      this.WriteValue(value);
      this.WriteEndTag();
    }


    /// <summary>
    /// Writes a tag value.
    /// </summary>
    /// <exception cref="ArgumentException">Thrown when the type of the tag is invalid.</exception>
    /// <param name="tag">The <see cref="ITag"/> to write.</param>
    public void WriteValue(ITag tag)
    {
      switch (tag.Type)
      {
        case TagType.Byte:
          this.WriteValue(((TagByte)tag).Value);
          break;

        case TagType.Short:
          this.WriteValue(((TagShort)tag).Value);
          break;

        case TagType.Int:
          this.WriteValue(((TagInt)tag).Value);
          break;

        case TagType.Long:
          this.WriteValue(((TagLong)tag).Value);
          break;

        case TagType.Float:
          this.WriteValue(((TagFloat)tag).Value);
          break;

        case TagType.Double:
          this.WriteValue(((TagDouble)tag).Value);
          break;

        case TagType.ByteArray:
          this.WriteValue(((TagByteArray)tag).Value);
          break;

        case TagType.String:
          this.WriteValue(((TagString)tag).Value);
          break;

        case TagType.List:
          this.WriteValue(((TagList)tag).Value);
          break;

        case TagType.Compound:
          this.WriteValue(((TagCompound)tag).Value);
          break;

        case TagType.IntArray:
          this.WriteValue(((TagIntArray)tag).Value);
          break;


        default:
          throw new ArgumentException("Unrecognized or unsupported tag type.", nameof(tag));
      }
    }
  }
}
