

 //------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using NUnit.Framework;

namespace Cyotek.Data.Nbt.Tests
{
  [TestFixture]
  public partial class TagByteArrayTests : TestBase
  {
    [Test]
    public void Constructor_sets_name()
    {
      // arrange
      TagByteArray target;
      string expected;
      string actual;

      expected = "Alphatag";

      // act
      target = new TagByteArray(expected);

      // assert
      actual = target.Name;
      Assert.AreEqual(expected, actual);
    }

    [Test]
    public void Constructor_sets_default_name()
    {
      // arrange
      TagByteArray target;
      string expected;
      string actual;

      expected = string.Empty;

      // act
      target = new TagByteArray();

      // assert
      actual = target.Name;
      Assert.AreEqual(expected, actual);
    }

    [Test]
    public void Constructor_sets_default_value()
    {
      // arrange
      TagByteArray target;
      byte[] expected;
      byte[] actual;

      expected = new byte[0];

      // act
      target = new TagByteArray();

      // assert
      actual = target.Value;
      Assert.AreEqual(expected, actual);
    }

    [Test]
    public void Constructor_sets_value()
    {
      // arrange
      TagByteArray target;
      byte[] expected;
      byte[] actual;

      expected = new byte[] { 2, 4, 8, 16, 32, 64, 128 };

      // act
      target = new TagByteArray(string.Empty, expected);

      // assert
      actual = target.Value;
      Assert.AreEqual(expected, actual);
    }

    [Test]
    public void Constructor_sets_value_without_name()
    {
      // arrange
      TagByteArray target;
      byte[] expected;
      byte[] actual;

      expected = new byte[] { 2, 4, 8, 16, 32, 64, 128 };

      // act
      target = new TagByteArray(expected);

      // assert
      actual = target.Value;
      Assert.AreEqual(expected, actual);
    }

    [Test]
    public void SetValue_updates_value()
    {
      // arrange
      Tag target;
      byte[] expected;
      byte[] actual;

      target = new TagByteArray();

      expected = new byte[] { 2, 4, 8, 16, 32, 64, 128 };

      // act
      target.SetValue(expected);

      // assert
      actual = ((TagByteArray)target).Value;
      Assert.AreEqual(expected, actual);
    }

    [Test]
    public void GetValue_retrieves_value()
    {
      // arrange
      Tag target;
      byte[] expected;
      object actual;

      expected = new byte[] { 2, 4, 8, 16, 32, 64, 128 };

      target = TagFactory.CreateTag(expected);

      // act
      actual = target.GetValue();

      // assert
      Assert.AreEqual(expected, actual);
    }

    [Test]
    public void Equals_returns_true_for_matching_tag()
    {
      // arrange
      TagByteArray target;
      TagByteArray other;
      bool actual;

      target = new TagByteArray("alpha", new byte[] { 2, 4, 8, 16, 32, 64, 128 });
      other = new TagByteArray("alpha", new byte[] { 2, 4, 8, 16, 32, 64, 128 });

      // act
      actual = target.Equals(other);

      // assert
      Assert.IsTrue(actual);
    }

    [Test]
    public void Equals_returns_false_with_different_name()
    {
      // arrange
      TagByteArray target;
      TagByteArray other;
      bool actual;

      target = new TagByteArray("Alpha", new byte[] { 2, 4, 8, 16, 32, 64, 128 });
      other = new TagByteArray("Beta", new byte[] { 2, 4, 8, 16, 32, 64, 128 });

      // act
      actual = target.Equals(other);

      // assert
      Assert.IsFalse(actual);
    }

    [Test]
    public void Equals_returns_false_with_different_value()
    {
      // arrange
      TagByteArray target;
      TagByteArray other;
      bool actual;

      target = new TagByteArray(string.Empty, new byte[] { 2, 4, 8, 16, 32, 64, 128 });
      other = new TagByteArray(string.Empty, new byte[] { 2, 4, 8, 16, 32, 48, 128 });

      // act
      actual = target.Equals(other);

      // assert
      Assert.IsFalse(actual);
    }

    [Test]
    public void Type_returns_correct_value()
    {
      // arrange
      TagByteArray target;
      TagType expected;
      TagType actual;

      target = new TagByteArray();

      expected = TagType.ByteArray;

      // act
      actual = target.Type;

      // assert
      Assert.AreEqual(expected, actual);
    }

    [Test]
    public void GetHashCode_returns_same_value_for_matching_tags()
    {
      // arrange
      TagByteArray target;
      int actual;
      int expected;

      target = new TagByteArray("beta", new byte[] { 2, 4, 8, 16, 32, 64, 128 });

      expected = new TagByteArray("beta", new byte[] { 2, 4, 8, 16, 32, 64, 128 }).GetHashCode();

      // act
      actual = target.GetHashCode();

      // assert
      Assert.AreEqual(expected, actual);
    }

    [Test]
    public void GetHashCode_returns_different_values_with_different_name()
    {
      // arrange
      TagByteArray target;
      int actual;
      int notExpected;

      target = new TagByteArray("Alpha", new byte[] { 2, 4, 8, 16, 32, 64, 128 });

      notExpected = new TagByteArray("Beta", new byte[] { 2, 4, 8, 16, 32, 64, 128 }).GetHashCode();

      // act
      actual = target.GetHashCode();

      // assert
      Assert.AreNotEqual(notExpected, actual);
    }

    [Test]
    public void GetHashCode_returns_different_values_with_different_value()
    {
      // arrange
      TagByteArray target;
      int actual;
      int notExpected;

      target = new TagByteArray(string.Empty, new byte[] { 2, 4, 8, 16, 32, 64, 128 });

      notExpected = new TagByteArray(string.Empty, new byte[] { 2, 4, 8, 16, 32, 48, 128 }).GetHashCode();

      // act
      actual = target.GetHashCode();

      // assert
      Assert.AreNotEqual(notExpected, actual);
    }

    [Test]
    public void Value_can_be_set()
    {
      // arrange
      TagByteArray target;
      byte[] expected;
      byte[] actual;

      expected = new byte[] { 2, 4, 8, 16, 32, 64, 128 };

      target = new TagByteArray();

      // act
      target.Value = expected;

      // assert
      actual = target.Value;
      Assert.AreEqual(expected, actual);
    }

    [Test]
    public void ToValueString_returns_string_version_of_value()
    {
      // arrange
      TagByteArray target;
      string expected;
      string actual;

      expected = "02, 04, 08, 10, 20, 40, 80";

      target = new TagByteArray(string.Empty, new byte[] { 2, 4, 8, 16, 32, 64, 128 });

      // act
      actual = target.ToValueString();

      // assert
      Assert.AreEqual(expected, actual);
    }

    [Test]
    public void ToString_returns_string_version_of_tag()
    {
      // arrange
      TagByteArray target;
      string expected;
      string actual;

      expected = "[ByteArray: gamma] (7 items)";

      target = new TagByteArray("gamma", new byte[] { 2, 4, 8, 16, 32, 64, 128 });

      // act
      actual = target.ToString();

      // assert
      Assert.AreEqual(expected, actual);
    }
  }
}

