//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


using NUnit.Framework;

namespace Cyotek.Data.Nbt.Tests
{
  partial class TagFloatTests
  {
    [Test]
    public void Constructor_sets_name()
    {
      // arrange
      TagFloat target;
      string expected;
      string actual;

      expected = "Alphatag";

      // act
      target = new TagFloat(expected);

      // assert
      actual = target.Name;
      Assert.AreEqual(expected, actual);
    }

    [Test]
    public void Constructor_sets_default_name()
    {
      // arrange
      TagFloat target;
      string expected;
      string actual;

      expected = string.Empty;

      // act
      target = new TagFloat();

      // assert
      actual = target.Name;
      Assert.AreEqual(expected, actual);
    }

    [Test]
    public void Constructor_sets_default_value()
    {
      // arrange
      TagFloat target;
      float expected;
      float actual;

      expected = 0;

      // act
      target = new TagFloat();

      // assert
      actual = target.Value;
      Assert.AreEqual(expected, actual);
    }

    [Test]
    public void Constructor_sets_value()
    {
      // arrange
      TagFloat target;
      float expected;
      float actual;

      expected = 1.701412E+38F;

      // act
      target = new TagFloat(string.Empty, expected);

      // assert
      actual = target.Value;
      Assert.AreEqual(expected, actual);
    }

    [Test]
    public void Constructor_sets_value_without_name()
    {
      // arrange
      TagFloat target;
      float expected;
      float actual;

      expected = 1.701412E+38F;

      // act
      target = new TagFloat(expected);

      // assert
      actual = target.Value;
      Assert.AreEqual(expected, actual);
    }

    [Test]
    public void SetValue_updates_value()
    {
      // arrange
      Tag target;
      float expected;
      float actual;

      target = new TagFloat();

      expected = 1.701412E+38F;

      // act
      target.SetValue(expected);

      // assert
      actual = ((TagFloat)target).Value;
      Assert.AreEqual(expected, actual);
    }

    [Test]
    public void GetValue_retrieves_value()
    {
      // arrange
      Tag target;
      float expected;
      object actual;

      expected = 1.701412E+38F;

      target = TagFactory.CreateTag(expected);

      // act
      actual = target.GetValue();

      // assert
      Assert.AreEqual(expected, actual);
    }

    [Test]
    public void Equals_returns_true_for_matching_tag()
    {
      // arrange
      TagFloat target;
      TagFloat other;
      bool actual;

      target = new TagFloat("alpha", 1.701412E+38F);
      other = new TagFloat("alpha", 1.701412E+38F);

      // act
      actual = target.Equals(other);

      // assert
      Assert.IsTrue(actual);
    }

    [Test]
    public void Equals_returns_false_with_different_name()
    {
      // arrange
      TagFloat target;
      TagFloat other;
      bool actual;

      target = new TagFloat("Alpha", 1.701412E+38F);
      other = new TagFloat("Beta", 1.701412E+38F);

      // act
      actual = target.Equals(other);

      // assert
      Assert.IsFalse(actual);
    }

    [Test]
    public void Equals_returns_false_with_different_value()
    {
      // arrange
      TagFloat target;
      TagFloat other;
      bool actual;

      target = new TagFloat(string.Empty, 1.701412E+38F);
      other = new TagFloat(string.Empty, 1.134274E+38F);

      // act
      actual = target.Equals(other);

      // assert
      Assert.IsFalse(actual);
    }

    [Test]
    public void Type_returns_correct_value()
    {
      // arrange
      TagFloat target;
      TagType expected;
      TagType actual;

      target = new TagFloat();

      expected = TagType.Float;

      // act
      actual = target.Type;

      // assert
      Assert.AreEqual(expected, actual);
    }

    [Test]
    public void GetHashCode_returns_same_value_for_matching_tags()
    {
      // arrange
      TagFloat target;
      int actual;
      int expected;

      target = new TagFloat("beta", 1.701412E+38F);

      expected = new TagFloat("beta", 1.701412E+38F).GetHashCode();

      // act
      actual = target.GetHashCode();

      // assert
      Assert.AreEqual(expected, actual);
    }

    [Test]
    public void GetHashCode_returns_different_values_with_different_name()
    {
      // arrange
      TagFloat target;
      int actual;
      int notExpected;

      target = new TagFloat("Alpha", 1.701412E+38F);

      notExpected = new TagFloat("Beta", 1.701412E+38F).GetHashCode();

      // act
      actual = target.GetHashCode();

      // assert
      Assert.AreNotEqual(notExpected, actual);
    }

    [Test]
    public void GetHashCode_returns_different_values_with_different_value()
    {
      // arrange
      TagFloat target;
      int actual;
      int notExpected;

      target = new TagFloat(string.Empty, 1.701412E+38F);

      notExpected = new TagFloat(string.Empty, 1.134274E+38F).GetHashCode();

      // act
      actual = target.GetHashCode();

      // assert
      Assert.AreNotEqual(notExpected, actual);
    }

    [Test]
    public void Value_can_be_set()
    {
      // arrange
      TagFloat target;
      float expected;
      float actual;

      expected = 1.701412E+38F;

      target = new TagFloat();

      // act
      target.Value = expected;

      // assert
      actual = target.Value;
      Assert.AreEqual(expected, actual);
    }

    [Test]
    public void ToValueString_returns_string_version_of_value()
    {
      // arrange
      TagFloat target;
      string expected;
      string actual;

      expected = "1.701412E+38";

      target = new TagFloat(string.Empty, 1.701412E+38F);

      // act
      actual = target.ToValueString();

      // assert
      Assert.AreEqual(expected, actual);
    }

    [Test]
    public void ToString_returns_string_version_of_tag()
    {
      // arrange
      TagFloat target;
      string expected;
      string actual;

      expected = "[Float: gamma=1.701412E+38]";

      target = new TagFloat("gamma", 1.701412E+38F);

      // act
      actual = target.ToString();

      // assert
      Assert.AreEqual(expected, actual);
    }
  }
}

