//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


using NUnit.Framework;

namespace Cyotek.Data.Nbt.Tests
{
  [TestFixture]
  public partial class TagIntTests : TestBase
  {
    [Test]
    public void Constructor_sets_name()
    {
      // arrange
      TagInt target;
      string expected;
      string actual;

      expected = "Alphatag";

      // act
      target = new TagInt(expected);

      // assert
      actual = target.Name;
      Assert.AreEqual(expected, actual);
    }

    [Test]
    public void Constructor_sets_default_name()
    {
      // arrange
      TagInt target;
      string expected;
      string actual;

      expected = string.Empty;

      // act
      target = new TagInt();

      // assert
      actual = target.Name;
      Assert.AreEqual(expected, actual);
    }

    [Test]
    public void Constructor_sets_default_value()
    {
      // arrange
      TagInt target;
      int expected;
      int actual;

      expected = 0;

      // act
      target = new TagInt();

      // assert
      actual = target.Value;
      Assert.AreEqual(expected, actual);
    }

    [Test]
    public void Constructor_sets_value()
    {
      // arrange
      TagInt target;
      int expected;
      int actual;

      expected = 1073741823;

      // act
      target = new TagInt(string.Empty, expected);

      // assert
      actual = target.Value;
      Assert.AreEqual(expected, actual);
    }

    [Test]
    public void Constructor_sets_value_without_name()
    {
      // arrange
      TagInt target;
      int expected;
      int actual;

      expected = 1073741823;

      // act
      target = new TagInt(expected);

      // assert
      actual = target.Value;
      Assert.AreEqual(expected, actual);
    }

    [Test]
    public void SetValue_updates_value()
    {
      // arrange
      Tag target;
      int expected;
      int actual;

      target = new TagInt();

      expected = 1073741823;

      // act
      target.SetValue(expected);

      // assert
      actual = ((TagInt)target).Value;
      Assert.AreEqual(expected, actual);
    }

    [Test]
    public void GetValue_retrieves_value()
    {
      // arrange
      Tag target;
      int expected;
      object actual;

      expected = 1073741823;

      target = TagFactory.CreateTag(expected);

      // act
      actual = target.GetValue();

      // assert
      Assert.AreEqual(expected, actual);
    }

    [Test]
    public void Equals_returns_true_for_matching_tag()
    {
      // arrange
      TagInt target;
      TagInt other;
      bool actual;

      target = new TagInt("alpha", 1073741823);
      other = new TagInt("alpha", 1073741823);

      // act
      actual = target.Equals(other);

      // assert
      Assert.IsTrue(actual);
    }

    [Test]
    public void Equals_returns_false_with_different_name()
    {
      // arrange
      TagInt target;
      TagInt other;
      bool actual;

      target = new TagInt("Alpha", 1073741823);
      other = new TagInt("Beta", 1073741823);

      // act
      actual = target.Equals(other);

      // assert
      Assert.IsFalse(actual);
    }

    [Test]
    public void Equals_returns_false_with_different_value()
    {
      // arrange
      TagInt target;
      TagInt other;
      bool actual;

      target = new TagInt(string.Empty, 1073741823);
      other = new TagInt(string.Empty, 536870911);

      // act
      actual = target.Equals(other);

      // assert
      Assert.IsFalse(actual);
    }

    [Test]
    public void Type_returns_correct_value()
    {
      // arrange
      TagInt target;
      TagType expected;
      TagType actual;

      target = new TagInt();

      expected = TagType.Int;

      // act
      actual = target.Type;

      // assert
      Assert.AreEqual(expected, actual);
    }

    [Test]
    public void GetHashCode_returns_same_value_for_matching_tags()
    {
      // arrange
      TagInt target;
      int actual;
      int expected;

      target = new TagInt("beta", 1073741823);

      expected = new TagInt("beta", 1073741823).GetHashCode();

      // act
      actual = target.GetHashCode();

      // assert
      Assert.AreEqual(expected, actual);
    }

    [Test]
    public void GetHashCode_returns_different_values_with_different_name()
    {
      // arrange
      TagInt target;
      int actual;
      int notExpected;

      target = new TagInt("Alpha", 1073741823);

      notExpected = new TagInt("Beta", 1073741823).GetHashCode();

      // act
      actual = target.GetHashCode();

      // assert
      Assert.AreNotEqual(notExpected, actual);
    }

    [Test]
    public void GetHashCode_returns_different_values_with_different_value()
    {
      // arrange
      TagInt target;
      int actual;
      int notExpected;

      target = new TagInt(string.Empty, 1073741823);

      notExpected = new TagInt(string.Empty, 536870911).GetHashCode();

      // act
      actual = target.GetHashCode();

      // assert
      Assert.AreNotEqual(notExpected, actual);
    }

    [Test]
    public void Value_can_be_set()
    {
      // arrange
      TagInt target;
      int expected;
      int actual;

      expected = 1073741823;

      target = new TagInt();

      // act
      target.Value = expected;

      // assert
      actual = target.Value;
      Assert.AreEqual(expected, actual);
    }

    [Test]
    public void ToValueString_returns_string_version_of_value()
    {
      // arrange
      TagInt target;
      string expected;
      string actual;

      expected = "1073741823";

      target = new TagInt(string.Empty, 1073741823);

      // act
      actual = target.ToValueString();

      // assert
      Assert.AreEqual(expected, actual);
    }

    [Test]
    public void ToString_returns_string_version_of_tag()
    {
      // arrange
      TagInt target;
      string expected;
      string actual;

      expected = "[Int: gamma=1073741823]";

      target = new TagInt("gamma", 1073741823);

      // act
      actual = target.ToString();

      // assert
      Assert.AreEqual(expected, actual);
    }
  }
}

