 //------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using NUnit.Framework;

namespace Cyotek.Data.Nbt.Tests
{
  [TestFixture]
  public partial class TagIntArrayTests : TestBase
  {
    [Test]
    public void Constructor_sets_name()
    {
      // arrange
      TagIntArray target;
      string expected;
      string actual;

      expected = "Alphatag";

      // act
      target = new TagIntArray(expected);

      // assert
      actual = target.Name;
      Assert.AreEqual(expected, actual);
    }

    [Test]
    public void Constructor_sets_default_name()
    {
      // arrange
      TagIntArray target;
      string expected;
      string actual;

      expected = string.Empty;

      // act
      target = new TagIntArray();

      // assert
      actual = target.Name;
      Assert.AreEqual(expected, actual);
    }

    [Test]
    public void Constructor_sets_default_value()
    {
      // arrange
      TagIntArray target;
      int[] expected;
      int[] actual;

      expected = new int[0];

      // act
      target = new TagIntArray();

      // assert
      actual = target.Value;
      Assert.AreEqual(expected, actual);
    }

    [Test]
    public void Constructor_sets_value()
    {
      // arrange
      TagIntArray target;
      int[] expected;
      int[] actual;

      expected = new[] { 2190, 2994, 3248, 4294394 };

      // act
      target = new TagIntArray(string.Empty, expected);

      // assert
      actual = target.Value;
      Assert.AreEqual(expected, actual);
    }

    [Test]
    public void Constructor_sets_value_without_name()
    {
      // arrange
      TagIntArray target;
      int[] expected;
      int[] actual;

      expected = new[] { 2190, 2994, 3248, 4294394 };

      // act
      target = new TagIntArray(expected);

      // assert
      actual = target.Value;
      Assert.AreEqual(expected, actual);
    }

    [Test]
    public void SetValue_updates_value()
    {
      // arrange
      Tag target;
      int[] expected;
      int[] actual;

      target = new TagIntArray();

      expected = new[] { 2190, 2994, 3248, 4294394 };

      // act
      target.SetValue(expected);

      // assert
      actual = ((TagIntArray)target).Value;
      Assert.AreEqual(expected, actual);
    }

    [Test]
    public void GetValue_retrieves_value()
    {
      // arrange
      Tag target;
      int[] expected;
      object actual;

      expected = new[] { 2190, 2994, 3248, 4294394 };

      target = TagFactory.CreateTag(expected);

      // act
      actual = target.GetValue();

      // assert
      Assert.AreEqual(expected, actual);
    }

    [Test]
    public void Equals_returns_true_for_matching_tag()
    {
      // arrange
      TagIntArray target;
      TagIntArray other;
      bool actual;

      target = new TagIntArray("alpha", new[] { 2190, 2994, 3248, 4294394 });
      other = new TagIntArray("alpha", new[] { 2190, 2994, 3248, 4294394 });

      // act
      actual = target.Equals(other);

      // assert
      Assert.IsTrue(actual);
    }

    [Test]
    public void Equals_returns_false_with_different_name()
    {
      // arrange
      TagIntArray target;
      TagIntArray other;
      bool actual;

      target = new TagIntArray("Alpha", new[] { 2190, 2994, 3248, 4294394 });
      other = new TagIntArray("Beta", new[] { 2190, 2994, 3248, 4294394 });

      // act
      actual = target.Equals(other);

      // assert
      Assert.IsFalse(actual);
    }

    [Test]
    public void Equals_returns_false_with_different_value()
    {
      // arrange
      TagIntArray target;
      TagIntArray other;
      bool actual;

      target = new TagIntArray(string.Empty, new[] { 2190, 2994, 3248, 4294394 });
      other = new TagIntArray(string.Empty, new[] { 2190, 2994, 3248, 294394 });

      // act
      actual = target.Equals(other);

      // assert
      Assert.IsFalse(actual);
    }

    [Test]
    public void Type_returns_correct_value()
    {
      // arrange
      TagIntArray target;
      TagType expected;
      TagType actual;

      target = new TagIntArray();

      expected = TagType.IntArray;

      // act
      actual = target.Type;

      // assert
      Assert.AreEqual(expected, actual);
    }

    [Test]
    public void GetHashCode_returns_same_value_for_matching_tags()
    {
      // arrange
      TagIntArray target;
      int actual;
      int expected;

      target = new TagIntArray("beta", new[] { 2190, 2994, 3248, 4294394 });

      expected = new TagIntArray("beta", new[] { 2190, 2994, 3248, 4294394 }).GetHashCode();

      // act
      actual = target.GetHashCode();

      // assert
      Assert.AreEqual(expected, actual);
    }

    [Test]
    public void GetHashCode_returns_different_values_with_different_name()
    {
      // arrange
      TagIntArray target;
      int actual;
      int notExpected;

      target = new TagIntArray("Alpha", new[] { 2190, 2994, 3248, 4294394 });

      notExpected = new TagIntArray("Beta", new[] { 2190, 2994, 3248, 4294394 }).GetHashCode();

      // act
      actual = target.GetHashCode();

      // assert
      Assert.AreNotEqual(notExpected, actual);
    }

    [Test]
    public void GetHashCode_returns_different_values_with_different_value()
    {
      // arrange
      TagIntArray target;
      int actual;
      int notExpected;

      target = new TagIntArray(string.Empty, new[] { 2190, 2994, 3248, 4294394 });

      notExpected = new TagIntArray(string.Empty, new[] { 2190, 2994, 3248, 294394 }).GetHashCode();

      // act
      actual = target.GetHashCode();

      // assert
      Assert.AreNotEqual(notExpected, actual);
    }

    [Test]
    public void Value_can_be_set()
    {
      // arrange
      TagIntArray target;
      int[] expected;
      int[] actual;

      expected = new[] { 2190, 2994, 3248, 4294394 };

      target = new TagIntArray();

      // act
      target.Value = expected;

      // assert
      actual = target.Value;
      Assert.AreEqual(expected, actual);
    }

    [Test]
    public void ToValueString_returns_string_version_of_value()
    {
      // arrange
      TagIntArray target;
      string expected;
      string actual;

      expected = "2190, 2994, 3248, 4294394";

      target = new TagIntArray(string.Empty, new[] { 2190, 2994, 3248, 4294394 });

      // act
      actual = target.ToValueString();

      // assert
      Assert.AreEqual(expected, actual);
    }

    [Test]
    public void ToString_returns_string_version_of_tag()
    {
      // arrange
      TagIntArray target;
      string expected;
      string actual;

      expected = "[IntArray: gamma] (4 items)";

      target = new TagIntArray("gamma", new[] { 2190, 2994, 3248, 4294394 });

      // act
      actual = target.ToString();

      // assert
      Assert.AreEqual(expected, actual);
    }
  }
}

