//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


using NUnit.Framework;

namespace Cyotek.Data.Nbt.Tests
{
  [TestFixture]
  public partial class TagListTests : TestBase
  {
    [Test]
    public void Constructor_sets_name()
    {
      // arrange
      TagList target;
      string expected;
      string actual;

      expected = "Alphatag";

      // act
      target = new TagList(expected);

      // assert
      actual = target.Name;
      Assert.AreEqual(expected, actual);
    }

    [Test]
    public void Constructor_sets_default_name()
    {
      // arrange
      TagList target;
      string expected;
      string actual;

      expected = string.Empty;

      // act
      target = new TagList();

      // assert
      actual = target.Name;
      Assert.AreEqual(expected, actual);
    }

    [Test]
    public void Constructor_sets_default_value()
    {
      // arrange
      TagList target;
      TagCollection expected;
      TagCollection actual;

      expected = new TagCollection(TagType.Int);

      // act
      target = new TagList();

      // assert
      actual = target.Value;
      Assert.AreEqual(expected, actual);
    }

    [Test]
    public void Constructor_sets_value()
    {
      // arrange
      TagList target;
      TagCollection expected;
      TagCollection actual;

      expected = new TagCollection(TagType.Int) { 2, 4, 8, 16, 32, 64, 128, 256 };

      // act
      target = new TagList(string.Empty, expected);

      // assert
      actual = target.Value;
      Assert.AreEqual(expected, actual);
    }

    [Test]
    public void Constructor_sets_value_without_name()
    {
      // arrange
      TagList target;
      TagCollection expected;
      TagCollection actual;

      expected = new TagCollection(TagType.Int) { 2, 4, 8, 16, 32, 64, 128, 256 };

      // act
      target = new TagList(expected);

      // assert
      actual = target.Value;
      Assert.AreEqual(expected, actual);
    }

    [Test]
    public void SetValue_updates_value()
    {
      // arrange
      Tag target;
      TagCollection expected;
      TagCollection actual;

      target = new TagList();

      expected = new TagCollection(TagType.Int) { 2, 4, 8, 16, 32, 64, 128, 256 };

      // act
      target.SetValue(expected);

      // assert
      actual = ((TagList)target).Value;
      Assert.AreEqual(expected, actual);
    }

    [Test]
    public void GetValue_retrieves_value()
    {
      // arrange
      Tag target;
      TagCollection expected;
      object actual;

      expected = new TagCollection(TagType.Int) { 2, 4, 8, 16, 32, 64, 128, 256 };

      target = TagFactory.CreateTag(expected);

      // act
      actual = target.GetValue();

      // assert
      Assert.AreEqual(expected, actual);
    }

    [Test]
    public void Equals_returns_true_for_matching_tag()
    {
      // arrange
      TagList target;
      TagList other;
      bool actual;

      target = new TagList("alpha", new TagCollection(TagType.Int) { 2, 4, 8, 16, 32, 64, 128, 256 });
      other = new TagList("alpha", new TagCollection(TagType.Int) { 2, 4, 8, 16, 32, 64, 128, 256 });

      // act
      actual = target.Equals(other);

      // assert
      Assert.IsTrue(actual);
    }

    [Test]
    public void Equals_returns_false_with_different_name()
    {
      // arrange
      TagList target;
      TagList other;
      bool actual;

      target = new TagList("Alpha", new TagCollection(TagType.Int) { 2, 4, 8, 16, 32, 64, 128, 256 });
      other = new TagList("Beta", new TagCollection(TagType.Int) { 2, 4, 8, 16, 32, 64, 128, 256 });

      // act
      actual = target.Equals(other);

      // assert
      Assert.IsFalse(actual);
    }

    [Test]
    public void Equals_returns_false_with_different_value()
    {
      // arrange
      TagList target;
      TagList other;
      bool actual;

      target = new TagList(string.Empty, new TagCollection(TagType.Int) { 2, 4, 8, 16, 32, 64, 128, 256 });
      other = new TagList(string.Empty, new TagCollection(TagType.Int) { 2, 4, 8, 16, 32, 64, 128, 255 });

      // act
      actual = target.Equals(other);

      // assert
      Assert.IsFalse(actual);
    }

    [Test]
    public void Type_returns_correct_value()
    {
      // arrange
      TagList target;
      TagType expected;
      TagType actual;

      target = new TagList();

      expected = TagType.List;

      // act
      actual = target.Type;

      // assert
      Assert.AreEqual(expected, actual);
    }

    [Test]
    public void GetHashCode_returns_same_value_for_matching_tags()
    {
      // arrange
      TagList target;
      int actual;
      int expected;

      target = new TagList("beta", new TagCollection(TagType.Int) { 2, 4, 8, 16, 32, 64, 128, 256 });

      expected = new TagList("beta", new TagCollection(TagType.Int) { 2, 4, 8, 16, 32, 64, 128, 256 }).GetHashCode();

      // act
      actual = target.GetHashCode();

      // assert
      Assert.AreEqual(expected, actual);
    }

    [Test]
    public void GetHashCode_returns_different_values_with_different_name()
    {
      // arrange
      TagList target;
      int actual;
      int notExpected;

      target = new TagList("Alpha", new TagCollection(TagType.Int) { 2, 4, 8, 16, 32, 64, 128, 256 });

      notExpected = new TagList("Beta", new TagCollection(TagType.Int) { 2, 4, 8, 16, 32, 64, 128, 256 }).GetHashCode();

      // act
      actual = target.GetHashCode();

      // assert
      Assert.AreNotEqual(notExpected, actual);
    }

    [Test]
    public void GetHashCode_returns_different_values_with_different_value()
    {
      // arrange
      TagList target;
      int actual;
      int notExpected;

      target = new TagList(string.Empty, new TagCollection(TagType.Int) { 2, 4, 8, 16, 32, 64, 128, 256 });

      notExpected = new TagList(string.Empty, new TagCollection(TagType.Int) { 2, 4, 8, 16, 32, 64, 128, 255 }).GetHashCode();

      // act
      actual = target.GetHashCode();

      // assert
      Assert.AreNotEqual(notExpected, actual);
    }

    [Test]
    public void Value_can_be_set()
    {
      // arrange
      TagList target;
      TagCollection expected;
      TagCollection actual;

      expected = new TagCollection(TagType.Int) { 2, 4, 8, 16, 32, 64, 128, 256 };

      target = new TagList();

      // act
      target.Value = expected;

      // assert
      actual = target.Value;
      Assert.AreEqual(expected, actual);
    }

    [Test]
    public void ToValueString_returns_string_version_of_value()
    {
      // arrange
      TagList target;
      string expected;
      string actual;

      expected = "[2, 4, 8, 16, 32, 64, 128, 256]";

      target = new TagList(string.Empty, new TagCollection(TagType.Int) { 2, 4, 8, 16, 32, 64, 128, 256 });

      // act
      actual = target.ToValueString();

      // assert
      Assert.AreEqual(expected, actual);
    }

    [Test]
    public void ToString_returns_string_version_of_tag()
    {
      // arrange
      TagList target;
      string expected;
      string actual;

      expected = "[List: gamma] (8 items)";

      target = new TagList("gamma", new TagCollection(TagType.Int) { 2, 4, 8, 16, 32, 64, 128, 256 });

      // act
      actual = target.ToString();

      // assert
      Assert.AreEqual(expected, actual);
    }
  }
}

